//! The Libretro box-art archive, as a list of names to match against.
//!
//! # Why an index and not a URL guess
//!
//! The old code built a URL out of the folder name and six region suffixes and
//! asked for each in turn — up to `candidates × 6` sequential requests per game,
//! almost all of them 404s, and a hit only when the folder happened to be spelled
//! exactly as No-Intro spells it. Over 300 games that is roughly 5,400 requests
//! to find a few dozen covers.
//!
//! Real emulator frontends do not guess. They match against a canonical name
//! list. Libretro publishes one per system, and fetching it turns the same 300
//! games into ~190 requests: one index per console, cached for a week, then one
//! download per game that actually matched.
//!
//! # Two ways to fetch it, because one of them is not an API
//!
//! The primary source is the directory listing at `thumbnails.libretro.com`.
//! It is generated by nginx's autoindex: no versioning, no stability promise,
//! and it could be switched off tomorrow. So there is a fallback — the same
//! repository on GitHub, through the git-tree API, which *is* a documented
//! contract. The order is deliberate: the autoindex has no rate limit and gzips
//! to ~150 KB, while the GitHub API allows 60 requests an hour per IP, which is
//! plenty behind a 7-day cache but not something to spend by default.

use crate::name::{self, Normalized};
use crate::{ArtError, Confidence};
use std::collections::HashMap;

/// How long a successfully fetched index is trusted.
pub const INDEX_TTL_SECS: u64 = 7 * 24 * 60 * 60;
/// How long a failure is remembered, so a 300-game run during an outage does not
/// retry the same index 300 times.
pub const INDEX_FAIL_TTL_SECS: u64 = 60 * 60;

/// Below this, the fuzzy stage will not answer.
///
/// Measured with Python's `difflib.SequenceMatcher`, which is why
/// [`crate::name::similarity`] is that same algorithm hand-rolled rather than
/// whatever a similarity crate happens to implement.
pub const FUZZY_CUTOFF: f64 = 0.82;

/// If the best and second-best candidates are within this of each other and are
/// different games, the matcher declines rather than picking one.
pub const AMBIGUITY_MARGIN: f64 = 0.03;

/// One file in the archive.
#[derive(Debug, Clone)]
pub struct Entry {
    /// The file name without `.png`, exactly as the server spells it. What the
    /// download URL is built from — so it is a name the server gave us, never a
    /// name we invented.
    pub file: String,
    /// `file`, normalised. Its `groups` hold the region tags.
    pub norm: Normalized,
}

/// A parsed archive listing.
pub struct Index {
    pub entries: Vec<Entry>,
    /// Every spelling of every entry, to its positions. One game usually has
    /// several regional files, so the value is a list.
    by_key: HashMap<String, Vec<usize>>,
}

#[derive(Debug, Clone)]
pub struct Match {
    pub entry_index: usize,
    pub confidence: Confidence,
    /// Which of the caller's candidate names produced this.
    pub via: String,
}

impl Index {
    pub fn new(names: Vec<String>) -> Self {
        let entries: Vec<Entry> = names
            .into_iter()
            .map(|file| {
                let norm = name::normalize(&file);
                Entry { file, norm }
            })
            .collect();
        let mut by_key: HashMap<String, Vec<usize>> = HashMap::new();
        for (i, e) in entries.iter().enumerate() {
            for k in e.norm.keys() {
                if k.is_empty() {
                    continue;
                }
                by_key.entry(k.to_string()).or_default().push(i);
            }
        }
        Self { entries, by_key }
    }

    pub fn len(&self) -> usize {
        self.entries.len()
    }

    pub fn is_empty(&self) -> bool {
        self.entries.is_empty()
    }

    /// The best entry for any of these candidate names, or nothing.
    ///
    /// Every candidate is tried and the highest confidence wins — the old code
    /// returned on the first candidate that produced *any* bytes, which meant a
    /// dirty album tag beat a clean folder name purely by being first in the
    /// list.
    pub fn best_match(&self, candidates: &[String]) -> Option<Match> {
        let mut best: Option<Match> = None;
        for c in candidates {
            if let Some(m) = self.match_one(c) {
                let better = match &best {
                    None => true,
                    Some(b) => m.confidence > b.confidence,
                };
                if better {
                    let exact = m.confidence == Confidence::Exact;
                    best = Some(m);
                    // Nothing beats an exact match; stop paying for the rest.
                    if exact {
                        break;
                    }
                }
            }
        }
        best
    }

    /// Every entry somebody might have meant, best first.
    ///
    /// Deliberately looser than [`Index::best_match`], because it answers a
    /// different question. That one decides what to write into a folder with
    /// nobody watching, so two plausible games are a reason to decline; this
    /// one fills a list a person reads, where a second plausible game is a
    /// second row rather than a failure.
    pub fn candidates(&self, query: &str, limit: usize) -> Vec<usize> {
        let q = name::normalize(query);
        if q.key.is_empty() {
            return Vec::new();
        }
        let qkeys: Vec<&str> = q.keys().collect();
        let mut scored: Vec<(u8, usize)> = Vec::new();
        for (i, e) in self.entries.iter().enumerate() {
            if let Some(rank) = closeness(&qkeys, &e.norm) {
                scored.push((rank, i));
            }
        }
        // Closest first; then the best region, so the row a person sees first
        // is the one a download would have chosen; then the shortest name,
        // which is the game rather than a compilation that contains it.
        scored.sort_by(|a, b| {
            a.0.cmp(&b.0)
                .then_with(|| {
                    region_rank(&self.entries[a.1].norm.groups)
                        .cmp(&region_rank(&self.entries[b.1].norm.groups))
                })
                .then_with(|| self.entries[a.1].file.len().cmp(&self.entries[b.1].file.len()))
                .then_with(|| self.entries[a.1].file.cmp(&self.entries[b.1].file))
        });
        scored.into_iter().take(limit).map(|(_, i)| i).collect()
    }

    /// The entries whose name *is* this name, under any of its spellings.
    ///
    /// The cheap half of [`Index::candidates`], and the only part worth running
    /// across twenty archives that do not belong to this console: it is a hash
    /// lookup rather than a scan, and a fuzzy hit from an unrelated platform is
    /// a lottery — the same reasoning as [`crate::search`].
    pub fn exact(&self, query: &str) -> Vec<usize> {
        let q = name::normalize(query);
        let mut out: Vec<usize> = Vec::new();
        for k in q.keys() {
            if let Some(hits) = self.by_key.get(k) {
                for &i in hits {
                    if !out.contains(&i) {
                        out.push(i);
                    }
                }
            }
        }
        out.sort_by_key(|&i| region_rank(&self.entries[i].norm.groups));
        out
    }

    fn match_one(&self, candidate: &str) -> Option<Match> {
        let q = name::normalize(candidate);
        if q.key.is_empty() {
            return None;
        }

        // 1 & 2. Equality, on the primary spelling or any alternate. This is
        // where `Lufia 2` meets `Lufia II - Rise of the Sinistrals`.
        for k in q.keys() {
            if let Some(hits) = self.by_key.get(k) {
                if let Some(&i) = self.pick_region(hits) {
                    return Some(Match {
                        entry_index: i,
                        confidence: Confidence::Exact,
                        via: candidate.to_string(),
                    });
                }
            }
        }

        // 3 & 4. Subtitles, in both directions, and against every spelling —
        // not only the primary one. `Lufia 2` reaches
        // `Lufia II - Rise of the Sinistrals` through its roman alternate, which
        // is a *prefix* of that name rather than equal to it, so checking only
        // `q.key` here missed it entirely.
        for k in q.keys() {
            if k.is_empty() {
                continue;
            }
            // The archive has a subtitle we lack: `contra iii` →
            // `contra iii the alien wars`. Only when every such entry is the
            // same game, otherwise `final fantasy` matches a shelf of them.
            let prefix = format!("{k} ");
            let forward: Vec<usize> = self
                .entries
                .iter()
                .enumerate()
                .filter(|(_, e)| e.norm.keys().any(|ek| ek.starts_with(&prefix)))
                .map(|(i, _)| i)
                .collect();
            if !forward.is_empty() {
                if let Some(&i) = self.single_game(&forward) {
                    return Some(Match {
                        entry_index: i,
                        confidence: Confidence::High,
                        via: candidate.to_string(),
                    });
                }
            }

            // We have extra words the archive does not: `super metroid disc 1`.
            //
            // Only when those extra words are *packaging*. Without that check
            // this is the most dangerous rule in the file: `final fantasy
            // tactics a2` starts with `final fantasy `, so it matched
            // "Final Fantasy (USA)" — a different game, at High confidence,
            // which a bulk run would have written to disk unattended.
            let reverse: Vec<usize> = self
                .entries
                .iter()
                .enumerate()
                .filter(|(_, e)| {
                    e.norm.keys().any(|ek| {
                        !ek.is_empty()
                            && k.starts_with(&format!("{ek} "))
                            && only_packaging(&k[ek.len() + 1..])
                    })
                })
                .map(|(i, _)| i)
                .collect();
            if !reverse.is_empty() {
                if let Some(&i) = self.single_game(&reverse) {
                    return Some(Match {
                        entry_index: i,
                        confidence: Confidence::High,
                        via: candidate.to_string(),
                    });
                }
            }
        }

        // 5. Token subset, for word-order and punctuation differences.
        if q.tokens.len() >= 2 {
            let qs: std::collections::HashSet<&str> = q.tokens.iter().map(|s| s.as_str()).collect();
            let subset: Vec<usize> = self
                .entries
                .iter()
                .enumerate()
                .filter(|(_, e)| {
                    let es: std::collections::HashSet<&str> =
                        e.norm.tokens.iter().map(|s| s.as_str()).collect();
                    if !qs.is_subset(&es) {
                        return false;
                    }
                    let union = qs.union(&es).count();
                    union > 0 && qs.intersection(&es).count() as f64 / union as f64 >= 0.75
                })
                .map(|(i, _)| i)
                .collect();
            if !subset.is_empty() {
                if let Some(&i) = self.single_game(&subset) {
                    return Some(Match {
                        entry_index: i,
                        confidence: Confidence::Medium,
                        via: candidate.to_string(),
                    });
                }
            }
        }

        // 6. Fuzzy, with the ambiguity guard. Declining is strictly better than
        //    guessing when the output is a permanent write into someone's
        //    library — a missing cover is visibly missing, a wrong one is not.
        let mut scored: Vec<(f64, usize)> = Vec::new();
        for (i, e) in self.entries.iter().enumerate() {
            if e.norm.key.is_empty() {
                continue;
            }
            // Cheap length prefilter before the quadratic part.
            let (a, b) = (q.key.len() as f64, e.norm.key.len() as f64);
            if a.min(b) / a.max(b) < 0.6 {
                continue;
            }
            let s = name::similarity(&q.key, &e.norm.key);
            if s >= FUZZY_CUTOFF {
                scored.push((s, i));
            }
        }
        if scored.is_empty() {
            return None;
        }
        scored.sort_by(|a, b| b.0.partial_cmp(&a.0).unwrap_or(std::cmp::Ordering::Equal));
        let (top_score, top) = scored[0];
        let top_game = &self.entries[top].norm.key;
        if let Some(&(runner_score, runner)) = scored
            .iter()
            .find(|(_, i)| &self.entries[*i].norm.key != top_game)
        {
            let _ = runner;
            if top_score - runner_score < AMBIGUITY_MARGIN {
                return None;
            }
        }
        let same: Vec<usize> = scored
            .iter()
            .filter(|(_, i)| &self.entries[*i].norm.key == top_game)
            .map(|(_, i)| *i)
            .collect();
        self.pick_region(&same).map(|&i| Match {
            entry_index: i,
            confidence: Confidence::Low,
            via: candidate.to_string(),
        })
    }

    /// The one game these entries are all of, or nothing if they are several.
    ///
    /// Two titles are not automatically two games: an archive carries the same
    /// release under its Japanese and its Western name — *Final Fantasy Tactics
    /// A2 - Fuuketsu no Grimoire* and *… - Grimoire of the Rift* are one game.
    /// So when the names differ, look again at only the best-ranked region; if
    /// that leaves one title, it was a translation rather than a shelf.
    ///
    /// This does not loosen the guard where it matters. The entries behind a
    /// bare `final fantasy` are *Final Fantasy II*, *III* and *Mystic Quest*,
    /// all USA releases, so narrowing by region leaves three titles and the
    /// matcher still declines.
    fn single_game<'a>(&self, hits: &'a [usize]) -> Option<&'a usize> {
        let key_of = |i: usize| &self.entries[i].norm.key;
        let first = key_of(hits[0]);
        if hits.iter().all(|&i| key_of(i) == first) {
            return self.pick_region(hits);
        }

        let best = hits
            .iter()
            .map(|&i| region_rank(&self.entries[i].norm.groups))
            .min()?;
        let preferred: Vec<usize> = hits
            .iter()
            .copied()
            .filter(|&i| region_rank(&self.entries[i].norm.groups) == best)
            .collect();
        let first = key_of(preferred[0]).clone();
        if preferred.iter().all(|&i| *key_of(i) == first) {
            // `pick_region` needs a slice that outlives the call, and the
            // filtered set does not, so return the position from `hits`.
            let want = preferred[0];
            hits.iter().find(|&&i| i == want)
        } else {
            None
        }
    }

    /// Among several regional files for one game, the most useful one.
    fn pick_region<'a>(&self, hits: &'a [usize]) -> Option<&'a usize> {
        hits.iter().min_by_key(|&&i| region_rank(&self.entries[i].norm.groups))
    }
}

/// How closely an entry answers a query, smaller being closer, or `None` for
/// not at all: 0 the same name, 1 one name extends the other, 2 one contains
/// the other, 3 a fuzzy resemblance.
fn closeness(qkeys: &[&str], entry: &Normalized) -> Option<u8> {
    if entry.key.is_empty() {
        return None;
    }
    let mut best: Option<u8> = None;
    let note = |r: u8, best: &mut Option<u8>| {
        if best.is_none_or(|b| r < b) {
            *best = Some(r);
        }
    };
    for q in qkeys {
        if q.is_empty() {
            continue;
        }
        for ek in entry.keys() {
            if ek.is_empty() {
                continue;
            }
            if *q == ek {
                return Some(0);
            }
            if ek.starts_with(&format!("{q} ")) || q.starts_with(&format!("{ek} ")) {
                note(1, &mut best);
            } else if ek.contains(q) || q.contains(ek) {
                note(2, &mut best);
            } else {
                // The same length prefilter the fuzzy matcher uses, for the
                // same reason: similarity is the expensive part and two names
                // of very different lengths never clear the cutoff anyway.
                let (a, b) = (q.len() as f64, ek.len() as f64);
                if a.min(b) / a.max(b) >= 0.6 && name::similarity(q, ek) >= FUZZY_CUTOFF {
                    note(3, &mut best);
                }
            }
        }
    }
    best
}

/// Words that describe how a rip was packaged rather than what it is of.
///
/// Deliberately excludes anything that could name a different product —
/// `tactics`, `advance`, `remake`, `zero`. Those turn one game into another.
const PACKAGING: &[&str] = &[
    "ost", "osts", "soundtrack", "soundtracks", "original", "score", "bgm", "gamerip", "rip",
    "complete", "music", "disc", "disk", "cd", "vol", "volume", "pt", "part", "set", "bonus",
    "extras", "the", "a", "an", "and",
];

/// Is everything here packaging, rather than more of a title?
fn only_packaging(rest: &str) -> bool {
    let words: Vec<&str> = rest.split(' ').filter(|w| !w.is_empty()).collect();
    !words.is_empty()
        && words
            .iter()
            .all(|w| PACKAGING.contains(w) || w.chars().all(|c| c.is_ascii_digit()))
}

/// Lower is better. Prefer a release over a prototype, and a region whose box
/// art is in the language most of these collections are labelled in.
fn region_rank(groups: &[String]) -> (u8, u8) {
    let joined = groups.join(" ");
    let bad = if groups.iter().any(|g| {
        matches!(g.as_str(), "beta" | "proto" | "prototype" | "demo" | "sample" | "unl" | "pirate")
            || g.starts_with("rev ")
            || g.contains("virtual console")
            // No-Intro's markers for a hacked, pirated or translated dump —
            // `Pokemon Gold (199x)(Mars)(CN)[h TPU][p]`. The box art attached to
            // one of those is usually not the game's at all.
            || g == "h"
            || g == "p"
            || g == "t"
            || g.starts_with("h ")
            || g.starts_with("t+")
            || g.starts_with("t-")
    }) {
        1
    } else {
        0
    };
    let region = if joined.contains("usa, europe") {
        1
    } else if joined.contains("usa") {
        0
    } else if joined.contains("world") {
        2
    } else if joined.contains("europe") {
        3
    } else if joined.contains("japan") {
        5
    } else {
        4
    };
    (bad, region)
}

/// Pull the file names out of an nginx autoindex page.
///
/// By hand: this is generated HTML, not a document, and a parser dependency for
/// thirty lines of `href="…"` scanning would be the tail wagging the dog.
pub fn parse_autoindex(body: &str) -> Vec<String> {
    let mut out = Vec::new();
    for part in body.split("href=\"").skip(1) {
        let Some(end) = part.find('"') else { continue };
        let href = &part[..end];
        if href.starts_with("..") || href.starts_with('?') || href.starts_with('/') {
            continue;
        }
        let Some(decoded) = percent_decode(href) else { continue };
        if let Some(stem) = strip_png(&decoded) {
            out.push(stem.to_string());
        }
    }
    out
}

/// Pull them out of a GitHub git-tree response instead.
pub fn parse_github_tree(body: &str) -> Result<Vec<String>, ArtError> {
    let v: serde_json::Value =
        serde_json::from_str(body).map_err(|e| ArtError::Network(format!("bad tree JSON: {e}")))?;
    let Some(tree) = v.get("tree").and_then(|t| t.as_array()) else {
        return Err(ArtError::Network("tree response has no `tree`".into()));
    };
    Ok(tree
        .iter()
        .filter_map(|e| e.get("path").and_then(|p| p.as_str()))
        .filter_map(|p| strip_png(p).map(str::to_string))
        .collect())
}

fn strip_png(s: &str) -> Option<&str> {
    let bytes = s.as_bytes();
    if bytes.len() > 4 && s[s.len() - 4..].eq_ignore_ascii_case(".png") {
        Some(&s[..s.len() - 4])
    } else {
        None
    }
}

fn percent_decode(s: &str) -> Option<String> {
    let mut out = Vec::with_capacity(s.len());
    let b = s.as_bytes();
    let mut i = 0;
    while i < b.len() {
        if b[i] == b'%' && i + 2 < b.len() {
            let hi = (b[i + 1] as char).to_digit(16)?;
            let lo = (b[i + 2] as char).to_digit(16)?;
            out.push((hi * 16 + lo) as u8);
            i += 3;
        } else {
            out.push(b[i]);
            i += 1;
        }
    }
    String::from_utf8(out).ok()
}

/// Did a 200 response actually contain a listing?
///
/// The gate is "we parsed nothing at all", **not** a minimum count. A minimum
/// looks safer and is wrong: the PlayStation 4 archive held 20 covers and the
/// PlayStation 3 archive 67 when last counted, so any threshold in the dozens
/// would declare those broken forever.
pub fn looks_like_a_listing(body: &str, parsed: usize) -> bool {
    parsed > 0 || body.len() < 512
}

#[cfg(test)]
mod tests {
    use super::*;

    const AUTOINDEX: &str = r#"
<html><head><title>Index of /Nintendo - Super Nintendo Entertainment System/Named_Boxarts</title></head>
<body><table>
<tr><td><a href="?C=N;O=D">Name</a></td></tr>
<tr><td><a href="/">Parent</a></td></tr>
<tr><td><a href="../">Parent Directory</a></td></tr>
<tr><td><a href="Chrono%20Trigger%20%28USA%29.png">Chrono Trigger (USA).png</a></td></tr>
<tr><td><a href="Pocky%20%26%20Rocky%20%28USA%29.png">Pocky &amp; Rocky (USA).png</a></td></tr>
<tr><td><a href="readme.txt">readme.txt</a></td></tr>
</table></body></html>"#;

    #[test]
    fn the_autoindex_parser_takes_the_files_and_nothing_else() {
        let got = parse_autoindex(AUTOINDEX);
        assert_eq!(got, ["Chrono Trigger (USA)", "Pocky & Rocky (USA)"]);
    }

    #[test]
    fn the_github_tree_parser_agrees_with_it() {
        let json = r#"{"tree":[
            {"path":"Chrono Trigger (USA).png","type":"blob"},
            {"path":"Pocky & Rocky (USA).png","type":"blob"},
            {"path":"README.md","type":"blob"}]}"#;
        assert_eq!(parse_github_tree(json).unwrap(), ["Chrono Trigger (USA)", "Pocky & Rocky (USA)"]);
    }

    /// The sanity gate must not be a minimum count: real archives are tiny.
    #[test]
    fn a_small_but_real_archive_is_not_mistaken_for_a_broken_one() {
        let twenty = (0..20)
            .map(|i| format!("<a href=\"Game{i}.png\">x</a>"))
            .collect::<String>();
        let parsed = parse_autoindex(&twenty);
        assert_eq!(parsed.len(), 20);
        assert!(looks_like_a_listing(&twenty, parsed.len()), "20 covers is a real PS4 archive");
    }

    #[test]
    fn a_page_that_is_no_longer_a_listing_is_caught() {
        let body = "<html><body>".to_string() + &"nothing here. ".repeat(100) + "</body></html>";
        assert_eq!(parse_autoindex(&body).len(), 0);
        assert!(!looks_like_a_listing(&body, 0));
    }

    /// The picker's list, which is a different question from the matcher's
    /// answer: `final fantasy` is exactly the query [`Index::match_one`]
    /// declines because it cannot tell II from III, and exactly the one a
    /// person wants both rows for.
    #[test]
    fn a_list_offers_what_a_single_answer_has_to_decline() {
        let idx = index();
        assert!(idx.best_match(&["Final Fantasy".into()]).is_none(), "ambiguous, so no answer");
        let names: Vec<&str> =
            idx.candidates("Final Fantasy", 8).into_iter().map(|i| idx.entries[i].file.as_str()).collect();
        assert!(names.contains(&"Final Fantasy II (USA)"), "got {names:?}");
        assert!(names.contains(&"Final Fantasy III (USA)"), "got {names:?}");
    }

    /// The name itself first, then what merely contains it. Typing a game and
    /// getting its sequel at the top would be a list nobody scrolls past.
    #[test]
    fn the_closest_name_is_the_first_row() {
        let idx = index();
        let first = idx.candidates("Mega Man X", 8)[0];
        assert_eq!(idx.entries[first].file, "Mega Man X (USA)");
    }

    /// Every region, since which box art a person wants is the whole reason
    /// they opened a list, but the one a download would have taken first.
    #[test]
    fn every_region_is_offered_best_one_first() {
        let idx = index();
        let got: Vec<&str> =
            idx.exact("Demon's Crest").into_iter().map(|i| idx.entries[i].file.as_str()).collect();
        assert_eq!(got, ["Demon's Crest (USA)", "Demon's Crest (Europe)"]);
    }

    #[test]
    fn a_name_the_archive_does_not_have_offers_nothing() {
        assert!(index().exact("Halo").is_empty());
        assert!(index().candidates("Halo", 8).is_empty());
    }

    fn index() -> Index {
        Index::new(vec![
            "Chrono Trigger (USA)".into(),
            "Contra III - The Alien Wars (USA)".into(),
            "Lion King, The (USA)".into(),
            "Lufia II - Rise of the Sinistrals (USA)".into(),
            "Super Metroid (Japan, USA)".into(),
            "Final Fantasy II (USA)".into(),
            "Final Fantasy III (USA)".into(),
            "Demon's Crest (Europe)".into(),
            "Demon's Crest (USA)".into(),
            "Mega Man X (USA)".into(),
            "Mega Man X2 (USA)".into(),
        ])
    }

    fn matched(idx: &Index, q: &str) -> Option<(String, Confidence)> {
        idx.best_match(&[q.to_string()])
            .map(|m| (idx.entries[m.entry_index].file.clone(), m.confidence))
    }

    #[test]
    fn an_exact_name_matches_exactly() {
        let idx = index();
        assert_eq!(matched(&idx, "Chrono Trigger"), Some(("Chrono Trigger (USA)".into(), Confidence::Exact)));
    }

    /// The archive carries a subtitle the folder does not.
    #[test]
    fn a_missing_subtitle_is_not_a_missing_match() {
        let idx = index();
        let (file, c) = matched(&idx, "Contra III").unwrap();
        assert_eq!(file, "Contra III - The Alien Wars (USA)");
        assert_eq!(c, Confidence::High);
    }

    /// And the other direction.
    #[test]
    fn extra_words_of_ours_are_not_a_missing_match() {
        let idx = index();
        assert_eq!(matched(&idx, "Super Metroid Disc 1").map(|m| m.0), Some("Super Metroid (Japan, USA)".into()));
    }

    #[test]
    fn the_article_no_intro_moved_to_the_end_still_matches() {
        let idx = index();
        assert_eq!(matched(&idx, "The Lion King").map(|m| m.0), Some("Lion King, The (USA)".into()));
    }

    /// Two rules have to compose for this: the arabic/roman alternate, and the
    /// subtitle stage — `lufia ii` is a *prefix* of the archive's name, not
    /// equal to it, so the confidence is High rather than Exact and that is the
    /// honest answer.
    #[test]
    fn an_arabic_numeral_finds_a_roman_one() {
        let idx = index();
        let (file, c) = matched(&idx, "Lufia 2").unwrap();
        assert_eq!(file, "Lufia II - Rise of the Sinistrals (USA)");
        assert_eq!(c, Confidence::High);
    }

    /// And when the two spellings really are the whole name, it is Exact.
    #[test]
    fn a_numeral_alternate_with_no_subtitle_is_exact() {
        let idx = Index::new(vec!["Final Fantasy IV (USA)".into()]);
        let (file, c) = matched(&idx, "Final Fantasy 4").unwrap();
        assert_eq!(file, "Final Fantasy IV (USA)");
        assert_eq!(c, Confidence::Exact);
    }

    /// The guard that matters most. `Final Fantasy` could be either of two games
    /// here, and answering would be a coin flip written permanently to disk.
    #[test]
    fn an_ambiguous_name_gets_no_answer_rather_than_a_coin_flip() {
        let idx = index();
        assert_eq!(matched(&idx, "Final Fantasy"), None);
    }

    /// `X` is a name. If this ever starts returning Mega Man X2, the roman
    /// numeral table grew an `x` entry.
    #[test]
    fn mega_man_x_is_not_mega_man_10() {
        let idx = index();
        assert_eq!(matched(&idx, "Mega Man X").map(|m| m.0), Some("Mega Man X (USA)".into()));
    }

    #[test]
    fn the_usa_release_is_preferred_over_the_european_one() {
        let idx = index();
        assert_eq!(matched(&idx, "Demons Crest").map(|m| m.0), Some("Demon's Crest (USA)".into()));
    }

    /// The worst match this matcher has produced, and the reason the reverse
    /// subtitle stage is restricted.
    ///
    /// `final fantasy tactics a2` starts with `final fantasy `, so before the
    /// packaging check it resolved to *Final Fantasy* — a different game, at
    /// High confidence, meaning a bulk run would have written the wrong box art
    /// into the user's folder without asking. Seen live in the running app.
    #[test]
    fn a_longer_title_is_not_the_shorter_game_it_starts_with() {
        let idx = Index::new(vec![
            "Final Fantasy (USA)".into(),
            "Super Metroid (Japan, USA)".into(),
            "Mega Man (USA)".into(),
        ]);
        assert_eq!(matched(&idx, "Final Fantasy Tactics A2"), None);
        assert_eq!(matched(&idx, "Final Fantasy Tactics"), None);
        assert_eq!(matched(&idx, "Mega Man Zero 3"), None);
        assert_eq!(matched(&idx, "Mega Man Battle Network"), None);
        // ...while the case the rule exists for still works.
        assert_eq!(
            matched(&idx, "Super Metroid OST Disc 1").map(|m| m.0),
            Some("Super Metroid (Japan, USA)".into())
        );
    }

    /// One game under two regional titles is one game.
    #[test]
    fn a_japanese_and_a_western_title_are_not_two_games() {
        let idx = Index::new(vec![
            "Final Fantasy Tactics A2 - Fuuketsu no Grimoire (Japan)".into(),
            "Final Fantasy Tactics A2 - Grimoire of the Rift (Europe) (En,Fr,De,Es)".into(),
            "Final Fantasy Tactics A2 - Grimoire of the Rift (USA) (En,Fr,Es)".into(),
        ]);
        let (file, c) = matched(&idx, "Final Fantasy Tactics A2").unwrap();
        assert_eq!(file, "Final Fantasy Tactics A2 - Grimoire of the Rift (USA) (En,Fr,Es)");
        assert_eq!(c, Confidence::High);
    }

    /// ...but a shelf of sequels still is a shelf, and they share a region.
    #[test]
    fn narrowing_by_region_does_not_unlock_a_shelf_of_sequels() {
        let idx = Index::new(vec![
            "Final Fantasy II (USA)".into(),
            "Final Fantasy III (USA)".into(),
            "Final Fantasy - Mystic Quest (USA)".into(),
        ]);
        assert_eq!(matched(&idx, "Final Fantasy"), None);
    }

    #[test]
    fn something_absent_is_absent() {
        let idx = index();
        assert_eq!(matched(&idx, "Halo"), None);
        assert_eq!(matched(&idx, ""), None);
    }

    /// Every candidate is tried and the best wins, so a dirty tag cannot beat a
    /// clean folder name by being first.
    #[test]
    fn the_best_candidate_wins_not_the_first() {
        let idx = index();
        let m = idx
            .best_match(&["Contra 3 rip".to_string(), "Chrono Trigger".to_string()])
            .unwrap();
        assert_eq!(idx.entries[m.entry_index].file, "Chrono Trigger (USA)");
        assert_eq!(m.confidence, Confidence::Exact);
    }
}
